---
name: 02 CD - Redis Enterprise
on:
  push:
    branches:
      - main
    paths:
      - "redisenterprise/*.tf"
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose Environment"
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - dev
      terraform_action:
        description: "Terraform Action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"
      terraform_cli_version:
        description: "Terraform CLI Version"
        required: true
        default: "latest"
        type: string
      folder_name:
        description: "Folder Name to run terraform in"
        required: true
        default: "redisenterprise"
        type: string

jobs:
  dev_plan_and_apply:
    uses: ContosoBeach/int-dev-template/.github/workflows/cd-template.yaml@main
    name: Development

    if: ${{ (inputs.environment || 'All') == 'All' || (inputs.environment || 'All') == 'dev' }}
    permissions:
      id-token: write
      contents: read
    with:
      terraform_action: ${{ inputs.terraform_action }}
      root_module_folder_relative_path: ${{ inputs.folder_name }}
      name: dev
      display_name: Development
      runner_name: self-hosted
      environment_name_plan: dev-plan
      environment_name_apply: dev-apply
      dependent_environment: ""
      backend_azure_storage_account_container_name: ${{ inputs.folder_name }}
      terraform_cli_version: ${{ inputs.terraform_cli_version }}
