---
name: 01 Continuous Integration
on:
  workflow_dispatch:
    inputs:
      terraform_cli_version:
        description: "Terraform CLI Version"
        required: true
        default: "latest"
        type: string
      folder_name:
        description: "Folder Name to run terraform in"
        required: true
        default: "redisenterprise"
        type: string

jobs:
  validate:
    name: Validate Terraform
    runs-on: self-hosted
    steps:
      - name: Validate Terraform
        uses: ContosoBeach/int-dev-template/.github/actions/validate@main
        with:
          root_module_folder_relative_path: ${{ inputs.folder_name }}
          terraform_cli_version: ${{ inputs.terraform_cli_version }}

  dev_plan:
    uses: ContosoBeach/int-dev-template/.github/workflows/ci-template.yaml@main
    name: Development
    needs: validate
    permissions:
      id-token: write
      contents: read
    with:
      root_module_folder_relative_path: ${{ inputs.folder_name }}
      name: dev
      display_name: Development
      runner_name: self-hosted
      environment_name_plan: dev-plan
      environment_name_apply: dev-apply
      dependent_environment: ""
      backend_azure_storage_account_container_name: dev
      terraform_cli_version: ${{ inputs.terraform_cli_version }}
